name: "Deploy doumentation for the toolchain"
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  doc-build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build documentation
      uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: doc

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: doc/_build/html
