name: "Deploy doumentation for the toolchain"
on:
  push:
    branches:
    - sources

jobs:
  docs-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: sources
        path: sources
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "sources/toolchain/"
    - name: Commit changes
      run: |
        rm -rf main/toolchain
        cp -r sources/toolchain/_build/html main/toolchain
        cd main
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        directory: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
