name: "Deploy doumentation for the toolchain"
on:
  push:
    branches:
    - sources
  pull_request:
    branches:
    - sources

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "toolchain/"
